version: '3'
services:
  db:
    container_name: ${DATABASE_ENVIRONMENT}
    image: postgres
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./postgresql${DATABASE_ENVIRONMENT}:/var/lib/postgresql/data
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    labels:
      - environment=${DATABASE_ENVIRONMENT}
